import './globals.css'
import { Inter } from 'next/font/google'
import NextAuthProvideSession from './Providers/ProvideSession'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextCoffee',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang='pt-br'>
      <body className={inter.className}>
        <NextAuthProvideSession>
          {children}
        </NextAuthProvideSession>
      </body>
    </html>
  )
}
